#!/usr/bin/env python

"""
PE002: Even Fibonacci numbers
-----------------------------

Name: pe002.py

Author: Zdenek Nemec <zdenek.nemec@artin.cz>

Version: 1.2 (2017-04-22)

Synopsis:
    ``pe002.py``

Examples:
    ``pe002.py``

Description:
    Solution for Project Euler Problem 2 (https://projecteuler.net/problem=2).

    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms will be:

.. math::

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

..

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.
"""


LIMIT = 4000000  # Top Limit


# Solution: Sum ###############################################################

def solve_sum(limit):
    """
    Find all Fibonacci numbers under specified limit and calculate the sum of
    the even ones.
    """
    num = 1
    num_p = 0
    num_pp = 0
    sum_even = 0
    while (num <= limit):
        if (num % 2 == 0):
            sum_even += num
        num_pp = num_p
        num_p = num
        num = num_p + num_pp
    return sum_even


# Main ########################################################################

def main():
    result = solve_sum(LIMIT)
    print "Solution: Sum"
    print "\tThe sum of the even numbers of Fibonacci sequence under limit", LIMIT, "is", result

    return 0


if __name__ == "__main__":
    main()
